# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81eed9c206f0cdc116d216e6be7eecc2707310cbfaf6c89517dfe8a83fd0feedaa142edaae8497b9d2dad06dbe05c17d139bc5578e5a512cc339140ab7982329

test:
  secret_key_base: 5fd8ca3deb18eb8d788a82b4d953daee71fa5da959d67d46cdcd07cc8d9befc63519e863aa7d03db662d13fb2a11afc01323d855b4b42a54e87517e1f24ebef6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
